version: 2.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Build front-end
          command: |
              cd frontend
              npm install
              npm run build


  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout

      - run:
          name: Back-end build
          command: |
             echo "Version of npm : "
             npm -v
             

          
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
            name: test-front-end
            command: |
                cd frontend
                npm install
                npm run test
                
  test-backend:
    docker:
       - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: sudo apt-get install curl
      - run:
           name: smoke test
           command: |
             URL="https://www.google.com/"
             # Test if website exists
             if curl -s --head ${URL} 
             then
               exit 0
             else
               exit 1
             fi            
  scan-frontend:
    docker:
       - image: circleci/node:13.8.0
    steps:
       - checkout
       - run:
         command: 
            cd frontend
            npm audit --audit-level=critical

  scan-backend:
    docker:
       - image: circleci/node:13.8.0
    steps:
       - checkout
       - run:
         command: 
            cd backend
            npm audit --audit-level=critical

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - scan-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      
